apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx
    securityContext:
      runAsUser: 1010
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 443
      protocol: TCP
  restartPolicy: Always
  schedulerName: default-scheduler
  automountServiceAccountToken: false
  serviceAccount: zippy
  serviceAccountName: zippy